#!/usr/bin/env python3
"""Generate mobile manifest adapter from RusTok module manifests."""

from __future__ import annotations

import argparse
import pathlib
import tomllib


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Path to repository root containing crates/*/rustok-module.toml",
    )
    parser.add_argument(
        "--output",
        default=(
            "rustok_mobile/apps/rustok_admin_mobile/lib/registry/mobile_manifest.g.dart"
        ),
        help="Output dart file path",
    )
    return parser.parse_args()


def scan_modules(repo_root: pathlib.Path) -> list[dict[str, str]]:
    modules: list[dict[str, str]] = []
    for manifest in sorted(repo_root.glob("crates/*/rustok-module.toml")):
        data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        module = data.get("module", {})
        provides = data.get("provides", {})
        admin_ui = provides.get("admin_ui")
        if not isinstance(admin_ui, dict):
            continue

        slug = str(module.get("slug", "")).strip()
        if not slug:
            continue

        route_segment = str(admin_ui.get("route_segment", slug)).strip() or slug
        nav_label = str(admin_ui.get("nav_label", slug.title())).strip() or slug.title()
        module_key = f"rustok_{slug.replace('-', '_')}"

        modules.append(
            {
                "slug": slug,
                "module_key": module_key,
                "route_segment": route_segment,
                "nav_label": nav_label,
            }
        )
    return modules


def render(modules: list[dict[str, str]]) -> str:
    lines = [
        "// GENERATED CODE - DO NOT MODIFY BY HAND.",
        "// Generated by rustok_mobile/tooling/scripts/generate_mobile_manifest.py",
        "",
        "import 'package:app_module_contracts/app_module_contracts.dart';",
        "",
        "const generatedMobileManifest = <MobileModuleEntry>[",
    ]
    for module in modules:
        lines.extend(
            [
                "  MobileModuleEntry(",
                f"    moduleKey: '{module['module_key']}',",
                f"    routeSegment: '{module['route_segment']}',",
                (
                    "    nav: MobileNavMeta("
                    f"title: '{module['nav_label']}', icon: 'module'),"
                ),
                "  ),",
            ]
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    repo_root = pathlib.Path(args.repo_root).resolve()
    output = pathlib.Path(args.output).resolve()
    modules = scan_modules(repo_root)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(modules), encoding="utf-8")
    print(f"Generated {len(modules)} modules into {output}")


if __name__ == "__main__":
    main()
