// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by rustok_mobile/tooling/scripts/generate_mobile_manifest.py

import 'package:app_module_contracts/app_module_contracts.dart';

const generatedMobileManifest = <MobileModuleEntry>[
  MobileModuleEntry(
    moduleKey: 'rustok_blog',
    routeSegment: 'blog',
    nav: MobileNavMeta(title: 'Blog', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_channel',
    routeSegment: 'channels',
    nav: MobileNavMeta(title: 'Channels', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_comments',
    routeSegment: 'comments',
    nav: MobileNavMeta(title: 'Comments', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_commerce',
    routeSegment: 'commerce',
    nav: MobileNavMeta(title: 'Commerce', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_customer',
    routeSegment: 'customers',
    nav: MobileNavMeta(title: 'Customers', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_forum',
    routeSegment: 'forum',
    nav: MobileNavMeta(title: 'Forum', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_fulfillment',
    routeSegment: 'fulfillment',
    nav: MobileNavMeta(title: 'Fulfillment', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_index',
    routeSegment: 'index',
    nav: MobileNavMeta(title: 'Index', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_inventory',
    routeSegment: 'inventory',
    nav: MobileNavMeta(title: 'Inventory', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_media',
    routeSegment: 'media',
    nav: MobileNavMeta(title: 'Media', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_order',
    routeSegment: 'orders',
    nav: MobileNavMeta(title: 'Orders', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_outbox',
    routeSegment: 'outbox',
    nav: MobileNavMeta(title: 'Outbox', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_pages',
    routeSegment: 'pages',
    nav: MobileNavMeta(title: 'Pages', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_pricing',
    routeSegment: 'pricing',
    nav: MobileNavMeta(title: 'Pricing', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_product',
    routeSegment: 'product',
    nav: MobileNavMeta(title: 'Products', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_rbac',
    routeSegment: 'rbac',
    nav: MobileNavMeta(title: 'RBAC', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_region',
    routeSegment: 'regions',
    nav: MobileNavMeta(title: 'Regions', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_search',
    routeSegment: 'search',
    nav: MobileNavMeta(title: 'Search', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_seo',
    routeSegment: 'seo',
    nav: MobileNavMeta(title: 'SEO', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_tenant',
    routeSegment: 'tenant',
    nav: MobileNavMeta(title: 'Tenant', icon: 'module'),
  ),
  MobileModuleEntry(
    moduleKey: 'rustok_workflow',
    routeSegment: 'workflow',
    nav: MobileNavMeta(title: 'Workflow', icon: 'module'),
  ),
];
